name: Github Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  gh-pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: tecosaur/org-knit-action@v0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          export: pdf
          force_orphan: yes
